### PR TITLE
[Add] - Impersonate RDP session / MSOL Attack ( Azure ) / CertPotato

### PR DESCRIPTION
**Pull request by jenaye**
image

### CODE REVIEW

**Comment by jenaye** [comment]
image

**Comment by jenaye** [comment]
image
 add CME module
 
 https://github.com/Porchetta-Industries/CrackMapExec/pull/716

**Comment by jenaye** [comment]
image

Add certpotato cf https://sensepost.com/blog/2022/certpotato-using-adcs-to-privesc-from-virtual-and-network-service-accounts-to-local-system/

**Comment by Mayfly277** [comment]
thx mike, integrated by hand du to some issue with your file, but thx for the adds :+1:

**Pull request closed without merging**
